name: docker-compose-push
description: Push to repository with docker-compose
inputs:
  compose_file_path:
    description: The path to the compose file we're building (with trailing slash)
    type: string
    required: true

  compose_file_name:
    description: The name of the main compose file
    type: string
    required: true

  tags:
    description: "tags to push"
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker compose push
      shell: bash
      run: |
        serviceImage=$(yq  -r '.services.*.image' ${{ inputs.compose_file_path}}${{ inputs.compose_file_name}})
        substr=":"
        baseImage=${serviceImage%%$substr*}
        
        declare -a tagArray=(${{ inputs.tags }})

        for element in "${tagArray[@]}"; do
          imageTagName="${baseImage}:${element}"
          docker tag $serviceImage $imageTagName
          echo "pushing ${imageTagName}"
          docker push ${imageTagName}
        done
